# Site settings for Guangzhou Miqu Information Technology Co., Ltd.
title: MeeFun - Joy is Yours to Discover
email: support@meeefun.com
description: >-
  Guangzhou Miqu Information Technology Co., Ltd. specializes in mobile app development, 
  web application development, and mini-program development. We build friendly business 
  partnerships based on mutual benefit and provide quality product services with respect and trust.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: "Guangzhou Miqu Information Technology Co., Ltd."
slogan: "Joy is Yours to Discover"
industry: "Information Transmission, Software and Information Technology Services"
core_business: ["Mobile App Development", "Web Application Development", "Mini-Program Development"]
philosophy: "Building friendly business partnerships based on mutual benefit and providing quality product services with respect and trust."

# Social Media
twitter_username: miqu_tech
github_username: miqu-tech

# Build settings
# theme: minima  # Removed to avoid default blog pages
# plugins:       # Removed jekyll-feed plugin
#   - jekyll-feed

# Collections
collections:
  services:
    output: true
    permalink: /services/:name/
  team:
    output: true
    permalink: /team/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _posts/  # Exclude posts directory
